project_name: waktusolat
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386
    ldflags:
      - -s -w -X github.com/waktusolatmy/cli/common.VersionCli={{.Version}} -X github.com/waktusolatmy/cli/common.CommitCli={{.Commit}} -X github.com/waktusolatmy/cli/common.DateCli={{.Date}}
checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.sha256"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch
archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
